name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/* # Uses the latest LTS (Long Term Support) Node.js version

    - name: Install Node.js dependencies
      run: npm ci # 'npm ci' is preferred in CI for clean and fast installs based on package-lock.json

    - name: Install Playwright Browsers and System Dependencies
      # This command downloads the browsers (Chromium, Firefox, WebKit)
      # and installs their necessary system-level dependencies on Linux (like Ubuntu).
      run: npx playwright install --with-deps

    - name: Run All Tests
      # This command assumes 'npm run All_Tests' in your package.json
      # is configured to execute both Playwright and Cucumber tests.
      run: xvfb-run npm run All_Tests

    - name: Upload Test Reports
      
      if: ${{ !cancelled() }} # Only upload if the job wasn't cancelled
      uses: actions/upload-artifact@v4
      with:
        name: test-reports # A descriptive name for the uploaded artifact
        path: |
          test-results/
          playwright-report/ # Path to Playwright's default HTML report directory
        retention-days: 30 # How long to keep the artifact (e.g., 30 days)
